package collection;

public enum Items {
    MATH, LANGUAGE, LITERACY, GYMNASTICS, HISTORY,
    GEOGRAPHY, BIOLOGY, CHEMISTRY, PHYSICS, LABOR, ASTRONOMY, MUSIC,
    PAINT, INFORMATICS, DRAFTING, ECOLOGY, SOCIETY, PHILOSOPHY;
}
